name: Linux Docker build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - 'devel'
          # just use for devel

          # - '5.36'
          # - '5.34'
          # - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'
          # - '5.6'

    container:
          image: perldocker/perl-tester:${{ matrix.perl-version }}

    name: Perl ${{ matrix.perl-version }}
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Install zstd
      run: apt-get install -y zstd
    - name: Perl version
      run: perl -V
    - name: Install dependencies
      run: cpanm --quiet --installdeps --notest .
    - name: Help output
      run: perl bin/zipdetails --help
    - name: Build
      run: perl Makefile.PL && make
    - name: Test
      run: make test TEST_VERBOSE=1